server.port=${PORT:8080}
spring.application.name=api-gateway

app.frontend-url=${FRONTEND_URL}

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.hostname=${RAILWAY_STATIC_URL:localhost}
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=api-gateway:8080
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.routes[1].id=qma-service
spring.cloud.gateway.routes[1].uri=lb://QMA-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/quantities/**

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true