server.port=${PORT:8081}
spring.application.name=qma-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=${RAILWAY_STATIC_URL:localhost}
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=qma-service:8081
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15

spring.data.redis.url=${REDIS_URL}
#spring.data.redis.timeout=500ms
#spring.data.redis.connect-timeout=500ms
#spring.data.redis.lettuce.pool.max-active=8
#spring.data.redis.lettuce.pool.max-idle=8
#spring.data.redis.lettuce.pool.min-idle=2
#spring.data.redis.lettuce.pool.max-wait=200ms